### PR TITLE
DXE-2430 Sort property traffic targets by DC id asc and sort liveness tests by…

### PR DESCRIPTION
**Pull request by hightoxicity**
… name asc to ensure idempotency

Ensure better idempotency forcing sorting of :
- traffic targets, sorting elements by target datacenter ids asc
- liveness tests, sorting elements by liveness tests names asc

Thx for review

### CODE REVIEW

**Comment by Slonimskaia** [comment]
Hello @hightoxicity,

Thank you for your contribution. We will need some time to review these changes.

Best regards,
Tatiana

**Comment by Slonimskaia** [comment]
@hightoxicity I see that with these changes a few unit tests fail. Please address them, before we proceed reviewing your pull request

**Comment by hightoxicity** [comment]
> @hightoxicity I see that with these changes a few unit tests fail. Please address them, before we proceed reviewing your pull request

Hi [Slonimskaia] yes I just saw it, I need more work on my 2 PRs, I will let you know when it is fixed+ready.

Thx

**Comment by hightoxicity** [comment]
OK, I have figured out that some sorting operations are already done in more appropriate places (DiffSuppressFunc), and I have also understood that I have still modifications in the plan because this function is called on a per element basis for schema.TypeList and not as a whole. That is why if my property has same traffic targets at both sides but are declared in different order, it conduces in all cases the plan to have modifications. My current difficulty is that I have no predictable way to sort my inputs to match how it is sorted in akamai GTM (I am bulk importing properties) and I can not get an initial neutral terraform plan because of this.

DiffSuppressFunc+schema.TypeList behaviour is a known issue:
https://github.com/hashicorp/terraform-plugin-sdk/issues/477

Maybe something can be done adding a DiffSuppressFunc on the parent resource (in the property resource) but not sure.

**Comment by hightoxicity** [comment]
Closing it in favour of https://github.com/akamai/terraform-provider-akamai/pull/404

**Pull request closed without merging**
