### PR TITLE
Add Edge Hostname Resource

### PR DESCRIPTION
**Pull request by tpounds**
Adds a new edge hostname resource that can be used to create them independently from property resources. The idea is to support a configuration that looks like the following.

```
resource "akamai_edge_hostname" "example" {
  contract_id    = "ctr_XXX"
  domain_prefix  = "example.com"
  domain_suffix  = "edgesuite.net"   // e.g. akamized.net, edgesuite.net, edgekey.net
  group_id       = "grp_XXX"
  ipv6           = true
  product_id     = "prd_XXX"
}

resource "akamai_property" "example" {
   ...

  hostname = {
    cname_from     = "tpounds.example.com"
    cname_to         = "example.com"
    edge_hostname_id = "${akamai_edge_hostname.example.id}" // ehn_XXX
  }

   ...
}

```

### CODE REVIEW

**Comment by tpounds** [comment]
@dshafik I've updated the pull request to make property hostname/edge hostname associations explicit which makes it easier to combine new or existing edge hostnames with a new property.

**Comment by dshafik** [comment]
@tpounds I'm not as convinced this should be a separate resource for two reasons:

1. PAPI should allow you to assign hostnames before they are active, if you were to put in the `edge_hostname_id` it would create a dependency that will wait for the hostname to activate, extending the `apply` time when new hostnames are used.
2. Perhaps there is a way to incorporate secure hostnames in here also? These have _much_ more overhead in terms of complexity to create/update/configure them, but obviously are critical.

For (2), I'm thinking that I need to spend the time to figure out the requirements for secure hostnames vs regular hostnames, and see what the overlap is, and whether it would be easier to have it's own resource or if they can extend regular hostnames with the addition of some optional extra attributes.

**Comment by dshafik** [comment]
@tpounds where are we with this? I'd like to move forward with your proposal, I'm happy to help any way I can.

**Comment by tpounds** [comment]
@dshafik Sorry I haven't had a chance to revisit this recently due to other priorities. I still the implementation as a separate resource is the right approach, however, I'm open to reworking if you have some additional ideas/thoughts. In either case I'll need to spend some to fixup the code to get it to cleanly merge back to master.

**Comment by dshafik** [comment]
@tpounds we are hoping to allow PAPI to create secure edge hostnames in much the same way as regular edge hostnames, removing the need to use SPS (when using them with property manager), but I don't have a timeline on that, and it doesn't change the fact that you likely won't be able to switch between secure and not secure. 

Additionally, there is now our Standard TLS, which is non-PCI compliant TLS (SNI-based Let's Encrypt certs on our standard network) which I believe use a standard edge hostname but would be considered "secure". I'll reach out to confirm that and I think that will require `akamai_edge_hostname` with a `secure` flag, and `akamai_secure_edge_hostname`.

**Comment by tpounds** [comment]
@dshafik Should I reopen under the new [repo](https://github.com/terraform-providers/terraform-provider-akamai)?

**Comment by dshafik** [comment]
@tpounds no need, this now exists! 

See: https://www.terraform.io/docs/providers/akamai/r/edge_hostname.html

And because of how the new standard TLS works (e.g. it doesn't have to have a certificate and will be a regular EHN without one) we support both types of hostnames with one resource.

**Pull request closed without merging**
