### PR TITLE
Cleanup make targets

### PR DESCRIPTION
**Pull request by tpounds**
Cleanup build logic by inlining all static checks as Makefile targets. Adds `gofmt` option to check for code simplification opportunities.

### CODE REVIEW

**Comment by tpounds** [comment]
@dshafik Any feedback here?

**Comment by dshafik** [comment]
@tpounds I like these changes but I'll need to check with Hashicorp if they're OK with us deviating from the standard here; perhaps they will want to bring those upstream for all providers.

**Comment by tpounds** [comment]
Sounds good to me. Is there any reference I can look at to see what standards you are referring to?

**Comment by dshafik** [comment]
@tpounds these files are new with the breakout of providers to separate repos, so they were all the same at that time — rather than being a written/documented standard. You can see [any other provider](https://github.com/terraform-providers), but it won't give you much other than "oh, it's the same as this was".

**Comment by tpounds** [comment]
@dshafik Should I reopen under the new [repo](https://github.com/terraform-providers/terraform-provider-akamai)?

**Comment by dshafik** [comment]
@tpounds Apologies, I didn't realize that my force push closed ALL open PRs. That's not how I wanted to communicate to you!

You are absolutely welcome to re-submit to the new repo, we welcome your participation — it is however possible that this particular PR is no longer necessary.

**Pull request closed without merging**
