### PR TITLE
Implemented resourceSecureEdgeHostNameDelete in akamai_edge_hostname

### PR DESCRIPTION
**Pull request by identw**
https://github.com/akamai/terraform-provider-akamai/issues/369

### CODE REVIEW

**Comment by lkowalsk-akamai-com** [comment]
Thank you for your submission; however, this feature needs internal attention to implement correctly.

**Comment by identw** [comment]
@lkowalsk-akamai-com what is wrong?
I tested my code for my edge hostnames and the code is working correct. 

I leave here instructions on how to assemble the code with my correction:

```bash
git clone https://github.com/identw/terraform-provider-akamai.git
cd terraform-provider-akamai
docker run --rm -v $(pwd):/app --workdir /app --entrypoint /bin/sh docker.io/golang:1.20.10 -c "
  go mod download
  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o terraform-provider-akamai_v5.5.0 .
"
mkdir -p  ~/terraform/proivders/registry.terraform.io/akamai/akamai/5.5.0/linux_amd64
cp -v ./terraform-provider-akamai_v5.5.0 ~/terraform/proivders/registry.terraform.io/akamai/akamai/5.5.0/linux_amd64/
```

create file `~/.terraformrc` with content:
```hcl
provider_installation {
  filesystem_mirror {
    path    = "/home/your_user_name/terraform/proivders"
    include = ["registry.terraform.io/akamai/akamai"]
  }
  direct {
    exclude = ["registry.terraform.io/akamai/akamai"]
  }
}
```

For macos you need to use `GOOS=darwin GOARCH=amd64` and use dir `~/terraform/proivders/registry.terraform.io/akamai/akamai/5.5.0/darwin_amd64/`
For macos M1/M2/M3 you need to use `GOOS=darwin GOARCH=arm64` and use dir `~/terraform/proivders/registry.terraform.io/akamai/akamai/5.5.0/darwin_arm64/`

**Comment by lkowalsk-akamai-com** [comment]
@identw , your submission is sound and appreciated. The reason we closed the PR has more to do with the potential for someone to make a mistake and cause harm to their infrastructure. To protect our users, the responsibility and accountability for implementing something like this needs to be on Akamai.

**Comment by identw** [comment]
I can fix it to make my implementation correct, I just need to understand where I went wrong. It’s just that 329 days have passed since the issue https://github.com/akamai/terraform-provider-akamai/issues/369 and it’s unclear how long it will take to wait for the correct implementation =(

**Pull request closed without merging**
