### PR TITLE
Add Activation resource

### PR DESCRIPTION
**Pull request by tpounds**
Splits property activation into a separate resource which allows independent life cycle management between property changes and specific network activations.

```
// always use latest version for STAGING
resource "akamai_activation" "ex-staging" {
  network          = "STAGING"
  notify_emails    = [
    "noreply@example.com"
  ]
  property_id      = "${akamai_property.example.id}"
  property_version = "${akamai_property.example.version}"
}

// always use explicit version for PRODUCTION network
resource "akamai_activation" "ex-prod" {
  network          = "PRODUCTION"
  notify_emails    = [
    "noreply@example.com"
  ]
  property_id      = "${akamai_property.example.id}"
  property_version = "1"
}

resource "akamai_property" "example" {
   ...
}
```

### CODE REVIEW

**Comment by dshafik** [comment]
I understand what you're trying to do here, but how do you stop it from activating _every time_? 

It should probably renamed to `akamai_property_activation` just to distinguish it from other types of activations.

This is tricky because activations _do_ exist as a resource in the API, but they're really just to convey the status/result of an action, and are not user-editable (and once activated, they are immutable) — so the terraform resource doesn't model them directly.

**Comment by tpounds** [comment]
@dshafik Thanks for the feedback. Answers inlined below.

> I understand what you're trying to do here, but how do you stop it from activating every time?

Specific property versions are activated and that doesn't always correspond to the latest editable property version (e.g. v1 prod activated, v2 staging activated, v3 editable). The data model is a one-to-many relationship that is not captured by the existing nested activation schema. That is, when `activate = true` the property is immediately activated on the configured network. This is not desirable when iterating on changes through a peer reviewed process (e.g. `terraform plan` via pull request). You can workaround this issue by removing the nested activation fields from the property while editing but this completely side steps Terraform's resource life-cycle and state management. The separate activation resource provides a mechanism to mutate and manage the remote activation state including deactivations when the resource is removed from the configuration. This cannot be done with the existing schema.

> It should probably renamed to akamai_property_activation just to distinguish it from other types of activations.

Agreed. This sounds like a good idea to avoid possible collisions with future resources that might be added to the provider.

> This is tricky because activations do exist as a resource in the API, but they're really just to convey the status/result of an action, and are not user-editable (and once activated, they are immutable) — so the terraform resource doesn't model them directly.

Per my points above, the network activations have to be decoupled using explicit versions from the property resource. This avoids implicit activations across one or more networks when editing a property and allow Terraform to property map to the remote resource's CRUD life-cycle.

**Comment by dshafik** [comment]
@tpounds based on your previous response, can you go ahead and make the change to `akamai_property_activation` and fix up the PR and I'll go ahead and merge this change.

Thanks!

**Comment by tpounds** [comment]
@dshafik Should I reopen under the new [repo](https://github.com/terraform-providers/terraform-provider-akamai)?

**Comment by dshafik** [comment]
@tpounds based on this PR (in spirit at least), we have done exactly this in the new provider: https://www.terraform.io/docs/providers/akamai/r/property_activation.html

**Pull request closed without merging**
