### PR TITLE
Release/v1.2.1

### PR DESCRIPTION
**Pull request by piotrpio**
#### BUG FIXES:
* PAPI -- Fixed crash caused by passing computed cpCode as a variable in rules to akamai_property
* PAPI -- Deprecated "product" attribute in akamai_cp_code resource and changed it "product_id"

### CODE REVIEW

**Review by ellenbluth — APPROVED** [review]

**Comment by Tyrael** [comment]
when can we expect the v1.2.1 tag/release?

**Comment by piotrpio** [comment]
@Tyrael release is now available

**Comment by Tyrael** [comment]
thanks!

**Comment by Tyrael** [comment]
hm, https://registry.terraform.io/v1/providers/-/akamai/versions still lists 1.2.0 as the latest version even thought https://registry.terraform.io/providers/akamai/akamai/latest shows the 1.2.1 release, maybe it takes some time to be updated there

**Comment by Tyrael** [comment]
hm, https://registry.terraform.io/v1/providers/akamai/akamai/versions doesn't list the 1.2.1 version, let me check if I can force to fetch the versions it from the vendor prefixed endpoint

**Comment by Tyrael** [comment]
nope, I'm still stuck on tf 0.12 so I can't use the provider source argument to use the namespaced versions
any check you can do something so that https://registry.terraform.io/v1/providers/-/akamai/versions can also list the new 1.2.1 release?
the same was as it lists the previous 1.2.0 release.

**Comment by Tyrael** [comment]
I'm going to create an issue about this, better place to track this there

**Comment by Tyrael** [comment]
lol, just as I was typing in the report 1.2.1 appeared in https://registry.terraform.io/v1/providers/-/akamai/versions and was able to install it.

**Pull request merged**
